force-app/main/default/objects/Contact/fields/Stripe_UID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_UID__c</fullName>
    <label>Stripe UID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricebookEntry/fields/Stripe_UID__c.field-meta.xml
<CustomField>
    <fullName>Stripe_UID__c</fullName>
    <label>Stripe UID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StripeEmail__e/StripeEmail__e.object-meta.xml
<CustomObject>
    <label>StripeEmail</label>
    <pluralLabel>StripeEmails</pluralLabel>
</CustomObject>

force-app/main/default/objects/StripeEmail__e/fields/CheckoutURL__c.field-meta.xml
<CustomField>
    <fullName>CheckoutURL__c</fullName>
    <label>CheckoutURL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/StripeEmail__e/fields/CustomerEmail__c.field-meta.xml
<CustomField>
    <fullName>CustomerEmail__c</fullName>
    <label>CustomerEmail</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StripeEmail__e/fields/OrderNumber__c.field-meta.xml
<CustomField>
    <fullName>OrderNumber__c</fullName>
    <label>OrderNumber</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/StripeEmail__e/fields/PaymentIntentURL__c.field-meta.xml
<CustomField>
    <fullName>PaymentIntentURL__c</fullName>
    <label>PaymentIntentURL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/StripeBillingConnector.cls
public with sharing class StripeBillingConnector {
    
    @future(callout=true)
    public static void handleOrderUpdate(String orderId)
    {
        System.debug(orderId);
        String priceId='';

        Order o = [select id, OrderNumber, CustomerAuthorizedById,Pricebook2Id from Order where id = :orderId];
        System.debug(o);

        // gets the Contact Data
        Contact contact = [select firstname, lastname, email, id from Contact where id = :o.CustomerAuthorizedById];

        // now gets the producs 
        for (OrderItem ordItem : [select id, ListPrice, Product2Id from OrderItem where OrderId= :o.Id])
        {
            System.debug(ordItem);
            // gets pricebook entry
            System.debug('select id, Stripe_UID__c from PricebookEntry where Product2Id = ' + ordItem.Product2Id + 'and Pricebook2Id = ' + o.Pricebook2Id + ' and UnitPrice= ' + ordItem.ListPrice + ' LIMIT 1 ');
            List<PricebookEntry> entries = [ select id, Stripe_UID__c from PricebookEntry where Product2Id = :ordItem.Product2Id and Pricebook2Id = :o.Pricebook2Id and UnitPrice= :ordItem.ListPrice LIMIT 1];
            for (PriceBookEntry entry : entries)
            {
                System.debug(entry);
                priceId = entry.Stripe_UID__c;
                System.debug(priceId);
            }
        }

        String StripeCustomerId = StripeApiHandler.createCustomer(contact.email,  contact.firstname ,contact.lastname, contact.id);
        System.debug(StripeCustomerId);
        System.debug('### stripecustomerId=' + StripeCustomerId);
        System.debug('### priceId=' + priceId);
        System.debug('### OrderNumber=' + o.OrderNumber);

        
        String StripeURLS=StripeApiHandler.createCheckoutSession(StripeCustomerId, priceId, o.OrderNumber);
        String StripeCheckoutSessionURL = StripeURLS.split(';',3)[0];
        String StripePaymentIntentURL = StripeURLS.split(';',3)[1];
        System.debug(StripeCheckoutSessionURL);
        System.debug(StripePaymentIntentURL);
        // generates a platform event
        List<StripeEmail__e> stripeEmail = new List<StripeEmail__e>();
        stripeEmail.add(new StripeEmail__e(CheckoutURL__c=StripeCheckoutSessionURL, 
        CustomerEmail__c=contact.email, 
        OrderNumber__c=o.OrderNumber,
        PaymentIntentURL__c=StripePaymentIntentURL));
        // Call method to publish events
        List<Database.SaveResult> results = EventBus.publish(stripeEmail);

        // updates contact
        contact.Stripe_UID__c=StripeCustomerId;
        update contact;

        }

    }